version: '3'

services:

  web-server:
    container_name: web-server
    build: ./web-server
    restart: always
    volumes:
      - ./web-server/conf.d:/etc/nginx/conf.d
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - client
      - server
      - smtp
      - postgres
      - mongo
      - cache        

  client:
    container_name: client
    build: ./client
    stdin_open: true
    restart: always
    volumes:
      - "./client:/App"
    ports:
      - "3000:3000"

  server:
    container_name: backend
    build: ./server
    restart: always
    volumes:
      - "./server:/backend"      
    ports:
      - "5000:5000" # For HTTP
      - "5001:5001" # For HTTPS

  smtp:
    container_name: smtp
    image: jeanberu/mailcatcher
    environment:
      - SMTP_PORT=${SMTP_PORT}
      - HTTP_PORT=${HTTP_PORT}
    ports:
      - "1025:1025"
      - "1080:1080"

  postgres:
    container_name: primary
    image: postgres:latest
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
      
  mongo:
    container_name: secondary
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "./data/mongodb:/data/db"
    ports:
      - "27017:27017"

  cache:
    container_name: cache
    image: redis
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - "./data/redis/redis-data:/var/lib/redis"
      - "./data/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    environment: 
      REDIS_REPLICATION_MODE: master    