remote_theme: stackbithq/stackbit-theme-fresh
title: ASP.NET <3 ReactJS
baseurl: /
url: https://github.com/Rubix982/ASP.NET-Core-5.0-Backend-ReactJS-Typescript-Frontend-Template
favicon: 'favicon.ico'
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Just a sample template to quickly power charge a project.
layout_style: overflow
palette: blue
header:
  title: ASP.NET <3 ReactJS
  tagline: Just a sample template to quickly power charge a project.
  profile_img: images/avatar.png
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; Stackbit-Fresh. All rights reserved.'
  links:
    - text: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
